### ISSUE TITLE
版本更新请求

### ISSUE THREAD

**Issue by EzraRT** [halo-sigs/charts#7]
halo的版本更新了不少了，chart的版本还很老，能更新一下不

**Comment by JohnNiang** [comment]
Halo 的版本可通过可自定义 `values.yaml` 配置来自定义 Halo 的版本，示例配置如下：

```yaml
image:
  registry: registry.fit2cloud.com
  repository: halo/halo
  tag: "2.18.0"
```

示例命令如下：

```bash
helm upgrade --create-namespace --install -n halo halo ./halo-1.1.0.tgz -f ~/halo/values.yaml
```

/kind support
